/* FREEREEL catalog — United States.
 *
 * Everything here is a legal, no-subscription way to watch. Nothing in this
 * file links to piracy, and nothing here needs a paid tier to be useful.
 *
 * ON STALENESS: free catalogues rotate constantly — a title that is free on
 * Tubi this month can be gone next month. So every title card also carries a
 * live "where is this free right now" lookup (JustWatch), which is the only
 * honest way to ship a list like this. Treat `where` as "this is where it
 * usually lives", and the lookup as the source of truth.
 *
 * confidence: 'pd'    = public domain, free forever, cannot rot
 *             'solid' = stable library placement, rarely moves
 *             'check' = rotates often, verify before you plan an evening on it
 */

const CATALOG_UPDATED = 'August 2026';
const REGION = 'United States';

/* ------------------------------------------------------------------ *
 * PLATFORMS — what each one actually gives you                        *
 * ------------------------------------------------------------------ */

const PLATFORMS = [
  {
    id: 'tubi',
    name: 'Tubi',
    owner: 'Fox',
    tier: 'major',
    signup: 'None. Account optional (only to sync your list).',
    offers: ['movies', 'tv', 'live', 'kids', 'anime', 'docs'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'The largest free movie library in the US — tens of thousands of films and TV seasons, plus a growing block of Tubi Originals and a live-channel tier.',
    best:
      'Horror and cult. It is not close: Tubi has the deepest legal free genre library in the country — 70s/80s slashers, giallo, exploitation, direct-to-video oddities, plus real licensed catalogue titles.',
    forYou:
      'This is your home base. Genre, cult, unscripted and a legitimately large licensed anime block all sit in one app, and it is on both Roku and the browser.',
    caveat: 'Ad breaks are frequent and unskippable. Catalogue rotates monthly.',
    url: 'https://tubitv.com/',
    hidden: false,
  },
  {
    id: 'pluto',
    name: 'Pluto TV',
    owner: 'Paramount',
    tier: 'major',
    signup: 'None at all.',
    offers: ['tv', 'movies', 'live', 'kids', 'anime'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      '250+ always-on linear channels laid out like a cable grid, plus an on-demand library. You do not pick a title — you pick a channel and it is already playing.',
    best:
      'Lean-back watching and single-show channels: 24/7 Forensic Files, 24/7 Star Trek, 24/7 MST3K, 24/7 Bob Ross, dedicated anime channels.',
    forYou:
      'The "I do not want to decide" button. Also the easiest anime on-ramp — the anime channels run all day and you just leave them on.',
    caveat: 'Live channels cannot be paused or rewound. On-demand can.',
    url: 'https://pluto.tv/',
    hidden: false,
  },
  {
    id: 'roku',
    name: 'The Roku Channel',
    owner: 'Roku',
    tier: 'major',
    signup: 'None on a Roku device. Free account for web/mobile.',
    offers: ['movies', 'tv', 'live', 'kids', 'docs'],
    devices: ['roku', 'web', 'mobile'],
    blurb:
      'Roku\'s own free service — films, TV, 400+ live channels and Roku Originals, built into every Roku device and also available in a browser.',
    best:
      'Already being there. On your Roku it is the lowest-friction free option, and its Kids & Family row is well curated.',
    forYou:
      'Since you are on Roku, this is zero-install. Good film rotation and a solid family section.',
    caveat: 'Web version is weaker than the device version.',
    url: 'https://therokuchannel.roku.com/',
    hidden: false,
  },
  {
    id: 'plex',
    name: 'Plex (free tier)',
    owner: 'Plex',
    tier: 'major',
    signup: 'Free account.',
    offers: ['movies', 'tv', 'live'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Separate from Plex\'s personal-media-server product, Plex runs a free ad-supported film/TV service plus live channels.',
    best: 'Discovery. Its universal watchlist tracks a title across every service you use and tells you when it goes free.',
    forYou:
      'Worth an account purely for the watchlist — it will notify you when something you want hits a free service.',
    caveat: 'The free library is smaller than Tubi\'s; the watchlist is the real draw.',
    url: 'https://watch.plex.tv/',
    hidden: false,
  },
  {
    id: 'xumo',
    name: 'Xumo Play',
    owner: 'Comcast / Charter',
    tier: 'major',
    signup: 'None.',
    offers: ['tv', 'movies', 'live'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb: 'Free live channels plus on-demand, in the same mould as Pluto.',
    best: 'Channel variety — it carries feeds the others do not.',
    forYou: 'Secondary. Check it when Pluto does not have the niche channel you want.',
    caveat: 'Interface is the weakest of the big free services.',
    url: 'https://play.xumo.com/',
    hidden: false,
  },
  {
    id: 'freestream',
    name: 'Sling Freestream',
    owner: 'DISH / Sling',
    tier: 'major',
    signup: 'None for the free tier.',
    offers: ['live', 'tv', 'movies', 'news'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Sling\'s free tier — 500+ live channels and on-demand, with no card and no trial clock.',
    best: 'News and live channel count. One of the broadest free live grids available.',
    forYou: 'Your best single stop for free live news channels.',
    caveat: 'It will upsell you to paid Sling constantly. Ignore it.',
    url: 'https://www.sling.com/freestream',
    hidden: false,
  },
  {
    id: 'youtube',
    name: 'YouTube (free films + official channels)',
    owner: 'Google',
    tier: 'major',
    signup: 'None.',
    offers: ['movies', 'tv', 'docs', 'live', 'kids', 'anime', 'news'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Beyond user uploads, YouTube runs an official ad-supported free-movies section, and many rights-holders post full films and full episodes on their own channels.',
    best:
      'Officially-posted full content that exists nowhere else free — Troma\'s entire catalogue, Taskmaster\'s full episodes, live international news.',
    forYou:
      'Underrated for exactly your taste. Cult distributors self-publish here, and it is the only free home for several shows you would otherwise pay for.',
    caveat: 'Stick to verified rights-holder channels; random full-movie uploads are piracy and get pulled.',
    url: 'https://www.youtube.com/feed/storefront?bp=ChBGRWF0dXJlZE1vdmllcxAB',
    hidden: false,
  },
  {
    id: 'primefree',
    name: 'Prime Video free-with-ads section',
    owner: 'Amazon',
    tier: 'major',
    signup: 'Free Amazon account (no Prime membership needed).',
    offers: ['movies', 'tv'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Amazon retired Freevee as a standalone app and folded its free ad-supported catalogue into Prime Video, where it is watchable without a Prime subscription.',
    best: 'Picking up the former Freevee originals and catalogue.',
    forYou: 'Only worth it if you already have an Amazon login. Filter to "Free with ads".',
    caveat: 'Buried in the UI and easy to confuse with paid rentals — check the price tag before you press play.',
    url: 'https://www.amazon.com/gp/video/storefront',
    hidden: false,
  },

  /* ---------- library card: the highest-quality free tier in America ---------- */
  {
    id: 'kanopy',
    name: 'Kanopy',
    owner: 'Kanopy / public libraries',
    tier: 'library',
    signup: 'Free public library card, or a university login.',
    offers: ['movies', 'docs', 'kids'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Arthouse and documentary streaming provided through your public library. Criterion Collection, A24, indie and world cinema, The Great Courses, and an ad-free Kanopy Kids section.',
    best:
      'Quality, full stop. This is the best free film library in the United States and almost nobody uses it. Zero ads.',
    forYou:
      'The serious half of your cult taste lives here — the Criterion horror and arthouse-weird titles that Tubi will never license.',
    caveat:
      'Credit-based: most libraries give 5–15 plays a month. Kanopy Kids and Great Courses usually do not consume credits.',
    url: 'https://www.kanopy.com/',
    hidden: true,
  },
  {
    id: 'hoopla',
    name: 'Hoopla',
    owner: 'Midwest Tape / public libraries',
    tier: 'library',
    signup: 'Free public library card.',
    offers: ['movies', 'tv', 'docs', 'kids'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Library streaming covering film, TV, comics, audiobooks and music. Borrow-based rather than credit-based.',
    best: 'Breadth and the comics library — full runs of major publishers, free.',
    forYou: 'Pairs with Kanopy. Different catalogue, same card. The comics alone justify it for the teen.',
    caveat: 'Monthly borrow limit set by your library, typically 4–10.',
    url: 'https://www.hoopladigital.com/',
    hidden: true,
  },

  /* ---------- public / nonprofit ---------- */
  {
    id: 'pbs',
    name: 'PBS',
    owner: 'Public Broadcasting Service',
    tier: 'public',
    signup: 'None for most; Passport needs a station donation.',
    offers: ['docs', 'tv', 'kids', 'news'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Full episodes of Frontline, NOVA, Nature, American Experience and more, streamed free with light or no advertising.',
    best: 'Documentary journalism. Frontline\'s full back catalogue is free and is genuinely world-class.',
    forYou: 'The non-junk-food option, and the single best thing on this whole list for the 6–12 year old.',
    caveat: 'Newest Masterpiece/drama episodes often sit behind a Passport donation for a window.',
    url: 'https://www.pbs.org/',
    hidden: false,
  },
  {
    id: 'pbskids',
    name: 'PBS Kids',
    owner: 'PBS',
    tier: 'public',
    signup: 'None. No account, no ads, no upsell.',
    offers: ['kids'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'A dedicated kids app and a 24/7 live channel. Everything on it is curriculum-designed and age-appropriate by construction.',
    best:
      'Being the only major kids service with no advertising and nothing to accidentally click into. There is no adult content to filter because there is none on the platform.',
    forYou:
      'For the 6–12 year old this is the safest thing you can hand them, and it needs no parental controls because the whole platform is the control.',
    caveat: 'Skews younger — a 12 year old may age out of much of it.',
    url: 'https://pbskids.org/',
    hidden: false,
  },
  {
    id: 'nasa',
    name: 'NASA+',
    owner: 'NASA',
    tier: 'public',
    signup: 'None.',
    offers: ['docs', 'live', 'kids'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb: 'NASA\'s own free, ad-free streaming service — documentary series, mission archives and live launch coverage.',
    best: 'Live launches, and genuinely well-made original documentary series.',
    forYou: 'Rare thing both kids will actually sit through, with zero ad risk.',
    caveat: 'Small catalogue. It is a supplement, not a destination.',
    url: 'https://plus.nasa.gov/',
    hidden: true,
  },
  {
    id: 'archive',
    name: 'Internet Archive',
    owner: 'Internet Archive (nonprofit)',
    tier: 'public',
    signup: 'None.',
    offers: ['movies', 'docs'],
    devices: ['web', 'mobile'],
    blurb:
      'The public-domain film vault: silent cinema, 50s sci-fi, noir, industrial and educational shorts, the Prelinger Archives.',
    best: 'Films that are free forever because nobody owns them any more. No ads, no rotation, downloadable.',
    forYou: 'The bedrock of your cult list — the pre-1930 horror and 50s creature features that can never be taken away.',
    caveat: 'Browser-first, no real TV app, and transfer quality varies wildly.',
    url: 'https://archive.org/details/movies',
    hidden: true,
  },

  /* ---------- niche / hidden gems ---------- */
  {
    id: 'kinocult',
    name: 'Kino Cult',
    owner: 'Kino Lorber',
    tier: 'niche',
    signup: 'None.',
    offers: ['movies'],
    devices: ['roku', 'web', 'mobile'],
    blurb:
      'A free ad-supported channel from arthouse distributor Kino Lorber, dedicated to cult, horror and transgressive cinema from their own restored catalogue.',
    best:
      'Restoration quality. These are the same 2K/4K restorations Kino sells on Blu-ray, streamed free.',
    forYou:
      'Probably the single best-kept secret for your exact taste. Curated by people who care, not by an algorithm.',
    caveat: 'Small, deliberately narrow catalogue. That is the point.',
    url: 'https://www.kinocult.com/',
    hidden: true,
  },
  {
    id: 'shout',
    name: 'Shout! TV',
    owner: 'Shout! Studios',
    tier: 'niche',
    signup: 'None.',
    offers: ['movies', 'tv', 'live'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Free service from the cult home-video label — Mystery Science Theater 3000, Roger Corman, 80s genre, plus 24/7 themed channels.',
    best: 'The largest legal free MST3K collection anywhere.',
    forYou: 'Cult and comedy in one place. MST3K is the exact intersection of both things you picked.',
    caveat: 'Site can be clunky; the Roku app is better.',
    url: 'https://www.shoutfactorytv.com/',
    hidden: true,
  },
  {
    id: 'midnightpulp',
    name: 'Midnight Pulp',
    owner: 'Cineverse',
    tier: 'niche',
    signup: 'None for the free tier.',
    offers: ['movies'],
    devices: ['roku', 'web', 'mobile'],
    blurb: 'Exploitation, grindhouse, Asian extreme, giallo and general midnight-movie programming.',
    best: 'Japanese and Korean genre cinema that the mainstream free services will not touch.',
    forYou: 'Where your cult taste goes once Tubi\'s surface layer is exhausted.',
    caveat: 'Some titles are paywalled into Cineverse\'s paid tier — the free ones are marked.',
    url: 'https://www.midnightpulp.com/',
    hidden: true,
  },
  {
    id: 'retrocrush',
    name: 'RetroCrush',
    owner: 'Cineverse',
    tier: 'niche',
    signup: 'None.',
    offers: ['anime'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'A free, ad-supported service devoted to classic and retro anime — properly licensed, often in both sub and dub.',
    best:
      'Pre-2000s anime. Lupin III, Astro Boy, Black Jack, Urusei Yatsura, Devilman, Cardcaptor Sakura, Rurouni Kenshin.',
    forYou:
      'The best free anime service in the US that almost nobody has heard of, and the answer to "free anime" that is not just Tubi.',
    caveat: 'Deliberately retro — do not come here for this season\'s simulcasts.',
    url: 'https://www.retrocrush.tv/',
    hidden: true,
  },
  {
    id: 'asiancrush',
    name: 'AsianCrush',
    owner: 'Cineverse',
    tier: 'niche',
    signup: 'None for the free tier.',
    offers: ['movies', 'tv'],
    devices: ['roku', 'web', 'mobile'],
    blurb: 'East and Southeast Asian cinema — horror, action, romance, thriller, plus drama series.',
    best: 'Korean and Japanese horror and thrillers, subtitled and legitimately licensed.',
    forYou: 'Direct feed for the J-horror / K-thriller vein of your taste.',
    caveat: 'Free tier is a subset of the paid catalogue.',
    url: 'https://www.asiancrush.com/',
    hidden: true,
  },
  {
    id: 'troma',
    name: 'Troma Movies (official YouTube)',
    owner: 'Troma Entertainment',
    tier: 'niche',
    signup: 'None.',
    offers: ['movies'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb:
      'Troma posts its own films, in full, free, on its own verified channel. This is the rights-holder giving it away, not a piracy upload.',
    best: 'Being the actual studio. The Toxic Avenger, Class of Nuke \'Em High, Tromeo & Juliet — all official.',
    forYou: 'Pure cult, zero cost, zero legal grey area.',
    caveat: 'Extremely not for the kids. Genuinely one of the crudest catalogues in film.',
    url: 'https://www.youtube.com/@TromaMovies',
    hidden: true,
  },
  {
    id: 'dust',
    name: 'DUST',
    owner: 'Gunpowder & Sky',
    tier: 'niche',
    signup: 'None.',
    offers: ['movies', 'tv'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb: 'Free sci-fi — short films, anthology series and features, on YouTube and as a FAST channel.',
    best: 'High-concept science fiction shorts, many with real budgets and real casts.',
    forYou: 'Perfect 10–20 minute format for a weeknight, and mostly fine for the teen.',
    caveat: 'Shorts by design; feature-length content is limited.',
    url: 'https://www.youtube.com/@watchdust',
    hidden: true,
  },
  {
    id: 'alter',
    name: 'ALTER',
    owner: 'Gunpowder & Sky',
    tier: 'niche',
    signup: 'None.',
    offers: ['movies'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb: 'DUST\'s horror sibling — free curated horror short films, many of which became feature deals.',
    best: 'Bite-sized dread. Several genuinely famous shorts live here (Lights Out, The Smiling Man).',
    forYou: 'Ten-minute horror hit when you do not have two hours.',
    caveat: 'Adults only in practice, despite the short runtimes.',
    url: 'https://www.youtube.com/@ALTER',
    hidden: true,
  },
  {
    id: 'comedydynamics',
    name: 'Comedy Dynamics Channel',
    owner: 'Comedy Dynamics',
    tier: 'niche',
    signup: 'None.',
    offers: ['tv', 'movies'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb: 'Free ad-supported channel from the biggest independent standup distributor in the US.',
    best: 'Full standup specials, free, from a rights-holder that owns hundreds of them.',
    forYou: 'Direct hit on the comedy half of your taste. Available as a FAST channel and inside Tubi/Roku.',
    caveat: 'Rotates; individual specials come and go.',
    url: 'https://www.comedydynamics.com/',
    hidden: true,
  },
  {
    id: 'localnow',
    name: 'Local Now',
    owner: 'Allen Media Group',
    tier: 'niche',
    signup: 'None.',
    offers: ['live', 'news', 'movies'],
    devices: ['roku', 'web', 'mobile', 'tv'],
    blurb: 'Free local news, weather and traffic for your ZIP code, assembled into a personalised channel, plus general FAST channels.',
    best: 'Actual local news without a cable subscription or an antenna.',
    forYou: 'The gap-filler an antenna does not cover — hyper-local, on demand.',
    caveat: 'Local segments are partly automated and can feel thin in small markets.',
    url: 'https://www.localnow.com/',
    hidden: true,
  },
];

/* Retired services people still search for — worth stating plainly so you do
 * not waste an evening hunting for an app that no longer exists. */
const RETIRED = [
  {
    name: 'Amazon Freevee',
    what: 'Shut down as a standalone service. Its free ad-supported catalogue moved inside Prime Video, watchable without a Prime subscription.',
    now: 'primefree',
  },
  {
    name: 'Peacock free tier',
    what: 'The no-cost Peacock tier was closed to new users. Peacock is now a paid service.',
    now: null,
  },
  {
    name: 'Pokémon TV',
    what: 'The free Pokémon app was discontinued; the series moved to paid services and the official Pokémon YouTube channel.',
    now: 'youtube',
  },
  {
    name: 'Redbox / Redbox Free Live TV',
    what: 'Ceased operations when its parent wound down. The FAST channels are gone.',
    now: null,
  },
];

/* ------------------------------------------------------------------ *
 * TITLES — the personalised watchlist                                 *
 * mood: fried | wired | creeped | laughs | awe | curious | company     *
 * age:  minimum sensible age — drives the profile filter               *
 * ------------------------------------------------------------------ */

const TITLES = [
  /* ---------------- cult / horror ---------------- */
  {
    id: 'notld',
    title: 'Night of the Living Dead',
    year: 1968,
    kind: 'film',
    mins: 96,
    genres: ['horror', 'cult'],
    where: ['tubi', 'archive', 'pluto', 'roku'],
    confidence: 'pd',
    age: 15,
    mood: ['creeped', 'wired'],
    why: 'The public-domain accident that founded modern horror. It is free on essentially every service simultaneously and always will be — the single most reliable pick on this entire list.',
  },
  {
    id: 'carnival',
    title: 'Carnival of Souls',
    year: 1962,
    kind: 'film',
    mins: 78,
    genres: ['horror', 'cult'],
    where: ['archive', 'tubi', 'kinocult'],
    confidence: 'pd',
    age: 13,
    mood: ['creeped', 'awe'],
    why: 'A $30,000 industrial-film director made one feature and accidentally invented the dread-logic that Lynch and Romero later built on. Public domain, 78 minutes, no gore — dream-unsettling rather than violent.',
  },
  {
    id: 'nosferatu',
    title: 'Nosferatu',
    year: 1922,
    kind: 'film',
    mins: 94,
    genres: ['horror', 'cult', 'silent'],
    where: ['archive', 'tubi', 'kanopy'],
    confidence: 'pd',
    age: 12,
    mood: ['creeped', 'awe'],
    why: 'Still genuinely eerie a century on, and the shadow-on-the-staircase shot is in your head already even if you have never seen it. Public domain because of a lost copyright case.',
  },
  {
    id: 'hausu',
    title: 'House (Hausu)',
    year: 1977,
    kind: 'film',
    mins: 88,
    genres: ['horror', 'cult', 'anime-adjacent'],
    where: ['kanopy'],
    confidence: 'solid',
    age: 15,
    mood: ['wired', 'laughs', 'creeped'],
    why: 'A haunted-house film scripted partly by a seven-year-old and shot like a toy commercial having a breakdown. If your cult taste has a ceiling, this is above it. Criterion title — which is exactly why it is on Kanopy and nowhere else free.',
  },
  {
    id: 'stalker',
    title: 'Stalker',
    year: 1979,
    kind: 'film',
    mins: 162,
    genres: ['scifi', 'arthouse'],
    where: ['kanopy'],
    confidence: 'solid',
    age: 15,
    mood: ['awe', 'curious'],
    why: 'The slowest, most beautiful science fiction ever committed to film. Needs a full evening and your whole attention. On Kanopy it costs one library credit and no money.',
  },
  {
    id: 'host',
    title: 'The Host',
    year: 2006,
    kind: 'film',
    mins: 120,
    genres: ['horror', 'scifi', 'comedy'],
    where: ['tubi', 'asiancrush', 'kanopy'],
    confidence: 'check',
    age: 14,
    mood: ['wired', 'creeped', 'laughs'],
    why: 'Bong Joon-ho\'s monster movie — a creature feature, a family comedy and a political satire running simultaneously, and it works as all three. Hits every genre you picked at once.',
  },
  {
    id: 'primer',
    title: 'Primer',
    year: 2004,
    kind: 'film',
    mins: 77,
    genres: ['scifi', 'cult'],
    where: ['tubi', 'plex'],
    confidence: 'check',
    age: 13,
    mood: ['wired', 'curious'],
    why: 'Time travel made for $7,000 by an engineer who refused to dumb it down. 77 minutes, and you will spend longer than that arguing about it afterwards.',
  },
  {
    id: 'coherence',
    title: 'Coherence',
    year: 2013,
    kind: 'film',
    mins: 89,
    genres: ['scifi', 'thriller'],
    where: ['tubi', 'plex', 'primefree'],
    confidence: 'check',
    age: 14,
    mood: ['wired', 'creeped'],
    why: 'Eight people at a dinner party, one comet, almost no budget and no script pages given to the cast. One of the most effective low-budget sci-fi premises of the last twenty years.',
  },
  {
    id: 'turbokid',
    title: 'Turbo Kid',
    year: 2015,
    kind: 'film',
    mins: 93,
    genres: ['scifi', 'horror', 'cult'],
    where: ['tubi', 'plex'],
    confidence: 'check',
    age: 16,
    mood: ['wired', 'laughs'],
    why: 'Post-apocalyptic BMX splatter comedy with a synth score, made by people who clearly grew up on exactly the VHS shelf this app is built around.',
  },
  {
    id: 'basketcase',
    title: 'Basket Case',
    year: 1982,
    kind: 'film',
    mins: 91,
    genres: ['horror', 'cult'],
    where: ['kinocult'],
    confidence: 'solid',
    age: 17,
    mood: ['wired', 'laughs', 'creeped'],
    why: '42nd Street grindhouse in its purest form, and Kino restored it beautifully — which makes Kino Cult the only place to see it free and looking correct.',
  },
  {
    id: 'mst3k',
    title: 'Mystery Science Theater 3000',
    year: 1988,
    kind: 'series',
    mins: 92,
    genres: ['comedy', 'cult', 'scifi'],
    where: ['shout', 'pluto', 'tubi'],
    confidence: 'solid',
    age: 10,
    mood: ['laughs', 'fried', 'company'],
    why: 'The exact midpoint of the two things you picked: cult trash and comedy, at once. Shout! has the biggest free legal collection and Pluto runs a 24/7 channel of it. Also the rare cult pick the 12-year-old can sit in on.',
  },
  {
    id: 'twilightzone',
    title: 'The Twilight Zone',
    year: 1959,
    kind: 'series',
    mins: 25,
    genres: ['scifi', 'horror', 'classic'],
    where: ['pluto', 'roku'],
    confidence: 'solid',
    age: 10,
    mood: ['creeped', 'awe', 'company'],
    why: 'Twenty-five minutes, self-contained, and the writing still outclasses most modern prestige TV. Works for you and works for the teen, which very little else on this list does.',
  },
  {
    id: 'toxie',
    title: 'The Toxic Avenger',
    year: 1984,
    kind: 'film',
    mins: 82,
    genres: ['horror', 'comedy', 'cult'],
    where: ['troma', 'tubi'],
    confidence: 'solid',
    age: 17,
    mood: ['laughs', 'wired'],
    why: 'Troma posts its own films free on its own channel, so this is the studio handing it to you. Tasteless in a way that is now historically significant. Absolutely not with kids in the room.',
  },
  {
    id: 'altershorts',
    title: 'ALTER horror shorts',
    year: 2026,
    kind: 'shorts',
    mins: 12,
    genres: ['horror'],
    where: ['alter'],
    confidence: 'solid',
    age: 16,
    mood: ['creeped'],
    why: 'When you want to be scared but do not have two hours. Ten-minute dread, curated, and several of these shorts became actual feature deals.',
  },
  {
    id: 'dustshorts',
    title: 'DUST sci-fi shorts',
    year: 2026,
    kind: 'shorts',
    mins: 15,
    genres: ['scifi'],
    where: ['dust'],
    confidence: 'solid',
    age: 12,
    mood: ['awe', 'curious', 'wired'],
    why: 'High-concept science fiction in 15-minute doses, much of it with real casts and real money behind it. One of the few genre picks the teen can watch with you.',
  },

  /* ---------------- anime ---------------- */
  {
    id: 'lupin',
    title: 'Lupin III',
    year: 1971,
    kind: 'series',
    mins: 24,
    genres: ['anime', 'comedy', 'action'],
    where: ['retrocrush', 'tubi', 'pluto'],
    confidence: 'solid',
    age: 13,
    mood: ['laughs', 'fried', 'company'],
    why: 'Gentleman-thief capers, endlessly rewatchable, and the tonal sweet spot between your comedy and your cult streaks. RetroCrush carries it properly licensed with both sub and dub.',
  },
  {
    id: 'blackjack',
    title: 'Black Jack',
    year: 1993,
    kind: 'series',
    mins: 25,
    genres: ['anime', 'drama', 'horror'],
    where: ['retrocrush'],
    confidence: 'solid',
    age: 15,
    mood: ['creeped', 'curious'],
    why: 'Tezuka\'s unlicensed-surgeon series — medical horror with a moral streak. Exactly the kind of thing that only survives free because RetroCrush exists.',
  },
  {
    id: 'urusei',
    title: 'Urusei Yatsura',
    year: 1981,
    kind: 'series',
    mins: 24,
    genres: ['anime', 'comedy', 'scifi'],
    where: ['retrocrush'],
    confidence: 'solid',
    age: 13,
    mood: ['laughs', 'fried'],
    why: 'Rumiko Takahashi\'s alien-girlfriend farce — the template a huge amount of anime comedy was built from. Pure fried-brain watching.',
  },
  {
    id: 'devilman',
    title: 'Devilman',
    year: 1972,
    kind: 'series',
    mins: 24,
    genres: ['anime', 'horror'],
    where: ['retrocrush'],
    confidence: 'check',
    age: 16,
    mood: ['creeped', 'wired'],
    why: 'Go Nagai\'s demon-horror original. Crude by modern standards and genuinely nasty, which is the appeal.',
  },
  {
    id: 'animechannels',
    title: 'Pluto TV anime channels',
    year: 2026,
    kind: 'live',
    mins: 0,
    genres: ['anime'],
    where: ['pluto'],
    confidence: 'solid',
    age: 13,
    mood: ['fried', 'company'],
    why: 'Several always-on anime channels. You do not choose an episode, you just turn it on — the correct format for a tired weeknight.',
  },
  {
    id: 'tubianime',
    title: 'Tubi\'s licensed anime block',
    year: 2026,
    kind: 'collection',
    mins: 0,
    genres: ['anime'],
    where: ['tubi'],
    confidence: 'check',
    age: 13,
    mood: ['fried', 'wired', 'company'],
    why: 'Surprisingly large and properly licensed — long-running shonen, older Toei catalogue, and a rotating set of films. The best free anime breadth in the US even though nobody thinks of Tubi first.',
  },

  /* ---------------- comedy / unscripted ---------------- */
  {
    id: 'taskmaster',
    title: 'Taskmaster',
    year: 2015,
    kind: 'series',
    mins: 47,
    genres: ['comedy', 'unscripted'],
    where: ['youtube'],
    confidence: 'solid',
    age: 13,
    mood: ['laughs', 'fried', 'company'],
    why: 'The production company posts full episodes free on its own official channel. Eighteen-plus series of the best comedy panel format in the world, for nothing, legally. The best value on this entire list.',
  },
  {
    id: 'forensicfiles',
    title: 'Forensic Files',
    year: 1996,
    kind: 'series',
    mins: 22,
    genres: ['docs', 'truecrime', 'unscripted'],
    where: ['pluto', 'roku', 'tubi'],
    confidence: 'solid',
    age: 14,
    mood: ['company', 'fried', 'curious'],
    why: 'The definitive background-television object. 22 minutes, self-contained, narrated in a monotone engineered for half-attention. Pluto runs it 24/7.',
  },
  {
    id: 'bobross',
    title: 'The Joy of Painting',
    year: 1983,
    kind: 'series',
    mins: 27,
    genres: ['unscripted', 'comfort'],
    where: ['pluto', 'youtube', 'roku'],
    confidence: 'solid',
    age: 0,
    mood: ['fried', 'company', 'awe'],
    why: 'A 24/7 channel of a calm man painting trees. The lowest-stakes thing in this app and the correct answer more often than you would think. Safe for literally everyone in the house.',
  },
  {
    id: 'unsolved',
    title: 'Unsolved Mysteries (classic)',
    year: 1987,
    kind: 'series',
    mins: 45,
    genres: ['unscripted', 'truecrime', 'creepy'],
    where: ['pluto', 'roku'],
    confidence: 'solid',
    age: 13,
    mood: ['creeped', 'company', 'fried'],
    why: 'Robert Stack in a trench coat in fog. Sits exactly between your unscripted streak and your creeped-out streak, and it is on a free 24/7 channel.',
  },
  {
    id: 'standup',
    title: 'Comedy Dynamics standup specials',
    year: 2026,
    kind: 'collection',
    mins: 62,
    genres: ['comedy'],
    where: ['comedydynamics', 'tubi', 'roku'],
    confidence: 'solid',
    age: 16,
    mood: ['laughs'],
    why: 'Hundreds of full specials from the largest independent standup distributor, free. An hour, no plot to follow, no commitment.',
  },
  {
    id: 'reno911',
    title: 'Reno 911!',
    year: 2003,
    kind: 'series',
    mins: 22,
    genres: ['comedy', 'unscripted'],
    where: ['pluto', 'roku', 'tubi'],
    confidence: 'check',
    age: 16,
    mood: ['laughs', 'fried'],
    why: 'Improvised, 22 minutes, no continuity to track. Ideal for the state where you want to laugh but cannot follow a plot.',
  },
  {
    id: 'mythbusters',
    title: 'MythBusters',
    year: 2003,
    kind: 'series',
    mins: 44,
    genres: ['unscripted', 'docs', 'science'],
    where: ['pluto', 'roku', 'tubi'],
    confidence: 'check',
    age: 10,
    mood: ['curious', 'company', 'fried'],
    why: 'One of the very few things that genuinely works for a 40-year-old, a teenager and a ten-year-old in the same room. Explosions plus method.',
  },

  /* ---------------- documentary ---------------- */
  {
    id: 'frontline',
    title: 'Frontline',
    year: 1983,
    kind: 'series',
    mins: 54,
    genres: ['docs', 'news'],
    where: ['pbs', 'youtube'],
    confidence: 'solid',
    age: 14,
    mood: ['curious'],
    why: 'Forty years of investigative documentary, the entire back catalogue free, no ads, no account. The single highest-quality free thing in American streaming.',
  },
  {
    id: 'nova',
    title: 'NOVA',
    year: 1974,
    kind: 'series',
    mins: 53,
    genres: ['docs', 'science'],
    where: ['pbs', 'youtube'],
    confidence: 'solid',
    age: 10,
    mood: ['curious', 'awe'],
    why: 'Science documentary that respects the audience. Works as family viewing with the 6–12 year old without being made for children.',
  },
  {
    id: 'nasadocs',
    title: 'NASA+ original series',
    year: 2026,
    kind: 'collection',
    mins: 45,
    genres: ['docs', 'science'],
    where: ['nasa'],
    confidence: 'solid',
    age: 8,
    mood: ['awe', 'curious'],
    why: 'Ad-free, government-made, genuinely well-shot. Zero risk of anything inappropriate appearing between segments, which matters in a mixed-age house.',
  },
  {
    id: 'greatcourses',
    title: 'The Great Courses',
    year: 2026,
    kind: 'collection',
    mins: 30,
    genres: ['docs', 'education'],
    where: ['kanopy'],
    confidence: 'solid',
    age: 13,
    mood: ['curious'],
    why: 'University lecture series that normally cost hundreds of dollars, free on Kanopy and usually not counted against your monthly credits.',
  },

  /* ---------------- kids 6–12 ---------------- */
  {
    id: 'wildkratts',
    title: 'Wild Kratts',
    year: 2011,
    kind: 'series',
    mins: 26,
    genres: ['kids', 'science', 'animation'],
    where: ['pbskids', 'pbs'],
    confidence: 'solid',
    age: 5,
    mood: ['curious', 'fried'],
    why: 'Animal science wrapped in an adventure cartoon. Ad-free on PBS Kids, and the 6–12 band is precisely its target.',
  },
  {
    id: 'oddsquad',
    title: 'Odd Squad',
    year: 2014,
    kind: 'series',
    mins: 26,
    genres: ['kids', 'comedy', 'math'],
    where: ['pbskids', 'pbs'],
    confidence: 'solid',
    age: 5,
    mood: ['laughs', 'curious'],
    why: 'Deadpan agency comedy that happens to teach maths. Genuinely funny to adults, which is rare and makes co-watching painless.',
  },
  {
    id: 'cyberchase',
    title: 'Cyberchase',
    year: 2002,
    kind: 'series',
    mins: 26,
    genres: ['kids', 'math', 'animation'],
    where: ['pbskids', 'pbs'],
    confidence: 'solid',
    age: 6,
    mood: ['curious'],
    why: 'Long-running maths adventure aimed squarely at the 6–12 band. Ad-free.',
  },
  {
    id: 'mollydenali',
    title: 'Molly of Denali',
    year: 2019,
    kind: 'series',
    mins: 26,
    genres: ['kids', 'animation'],
    where: ['pbskids', 'pbs'],
    confidence: 'solid',
    age: 5,
    mood: ['curious', 'company'],
    why: 'First US kids\' series led by an Alaska Native character, built around informational literacy. Ad-free, no upsell, no in-app anything.',
  },
  {
    id: 'kanopykids',
    title: 'Kanopy Kids',
    year: 2026,
    kind: 'collection',
    mins: 0,
    genres: ['kids', 'education'],
    where: ['kanopy'],
    confidence: 'solid',
    age: 3,
    mood: ['fried', 'curious'],
    why: 'Ad-free children\'s film and picture-book video through your library card, and it usually does not burn your monthly credits. The safest catalogue in this app after PBS Kids.',
  },
  {
    id: 'scishowkids',
    title: 'SciShow Kids',
    year: 2015,
    kind: 'series',
    mins: 5,
    genres: ['kids', 'science'],
    where: ['youtube'],
    confidence: 'solid',
    age: 5,
    mood: ['curious'],
    why: 'Five-minute science answers. Best used inside YouTube Kids rather than main YouTube — see the parental-controls section.',
  },
  {
    id: 'crashcourse',
    title: 'Crash Course',
    year: 2012,
    kind: 'series',
    mins: 12,
    genres: ['education', 'docs'],
    where: ['youtube'],
    confidence: 'solid',
    age: 12,
    mood: ['curious'],
    why: 'History, biology, literature and government in 12-minute episodes. Aimed at exactly the teen\'s age band and genuinely useful for schoolwork.',
  },
];

/* ------------------------------------------------------------------ *
 * LIVE — news, sports, channels                                       *
 * ------------------------------------------------------------------ */

const LIVE = [
  {
    group: 'Free live news — national',
    items: [
      { name: 'ABC News Live', where: ['roku', 'freestream', 'youtube'], note: '24/7 free feed, no account.' },
      { name: 'NBC News NOW', where: ['roku', 'freestream', 'youtube'], note: '24/7 free feed.' },
      { name: 'CBS News 24/7', where: ['pluto', 'roku', 'freestream'], note: 'Free, with local CBS feeds in many markets.' },
      { name: 'LiveNOW from FOX', where: ['youtube'], note: 'Raw unedited live events, no anchor commentary.' },
      { name: 'Bloomberg TV+', where: ['roku', 'pluto', 'freestream'], note: 'Free markets and business coverage.' },
      { name: 'C-SPAN', where: ['youtube'], note: 'Free on the web with no account — floor proceedings and hearings.' },
    ],
  },
  {
    group: 'Free live news — international',
    items: [
      { name: 'Al Jazeera English', where: ['youtube', 'freestream'], note: '24/7 official live stream.' },
      { name: 'DW (Deutsche Welle) English', where: ['youtube', 'freestream'], note: 'German public broadcaster, English feed.' },
      { name: 'France 24 English', where: ['youtube', 'freestream'], note: 'French public broadcaster, English feed.' },
      { name: 'Sky News', where: ['youtube'], note: 'UK feed, free on the official channel worldwide.' },
      { name: 'NHK World-Japan', where: ['youtube', 'roku'], note: 'Japanese public broadcaster in English. Strong documentary strand too.' },
    ],
  },
  {
    group: 'Live sports — the honest answer first',
    items: [
      {
        name: 'An over-the-air antenna',
        where: [],
        note: 'A one-time $25–40 indoor antenna gets you CBS, NBC, FOX, ABC and PBS free forever, in higher quality than any stream. That is NFL, March Madness, the Olympics, the World Series and the Super Bowl at no recurring cost. There is no streaming service that beats this, and it is the single most underused legal option in America.',
        star: true,
      },
      { name: 'Tubi live sports', where: ['tubi'], note: 'Fox has used Tubi for free simulcasts of major events, including a Super Bowl.' },
      { name: 'The Roku Sports Channel', where: ['roku'], note: 'Free highlights, replays and some live events.' },
      { name: 'CBS Sports Golazo Network', where: ['pluto', 'roku', 'freestream'], note: 'Free 24/7 soccer channel — highlights and some live matches.' },
      { name: 'The NFL Channel', where: ['pluto', 'roku', 'tubi'], note: 'Free NFL programming and highlights, though not full live regular-season games.' },
    ],
  },
  {
    group: 'Sports highlights — official, free, immediate',
    items: [
      { name: 'NFL / NBA / MLB / NHL official channels', where: ['youtube'], note: 'Full condensed games and same-night highlights, posted by the leagues themselves.' },
      { name: 'F1 official channel', where: ['youtube'], note: 'Free race highlights posted shortly after each Grand Prix.' },
      { name: 'UFC official channel', where: ['youtube'], note: 'Free fight highlights and full preliminary bouts.' },
    ],
  },
  {
    group: 'General live TV grids',
    items: [
      { name: 'Pluto TV', where: ['pluto'], note: '250+ channels, cable-style grid, zero signup. The best free lean-back grid.' },
      { name: 'Sling Freestream', where: ['freestream'], note: '500+ free channels, the broadest count available free.' },
      { name: 'The Roku Channel live tab', where: ['roku'], note: '400+ channels, already installed on your device.' },
      { name: 'Xumo Play', where: ['xumo'], note: 'Carries some feeds the others do not.' },
      { name: 'Local Now', where: ['localnow'], note: 'Your ZIP code\'s local news and weather without an antenna.' },
    ],
  },
];

/* ------------------------------------------------------------------ *
 * PARENTAL CONTROLS — setup that actually holds                       *
 * ------------------------------------------------------------------ */

const CONTROLS = [
  {
    name: 'Router-level DNS filtering',
    tier: 'Do this one first',
    star: true,
    steps: [
      'In your router\'s admin page, set the DNS servers to Cloudflare for Families (1.1.1.3 and 1.0.0.3) or OpenDNS FamilyShield (208.67.222.123 and 208.67.220.123).',
      'Both block adult content at the network level, free, with no software installed.',
      'Reboot the router, then reboot the Roku so it picks up the new DNS.',
    ],
    why: 'This is the only control that covers every device at once — including the Roku, which has no per-user profiles and therefore cannot be locked down properly any other way. In a house with a 6–12 year old and a teenager sharing hardware, this is the control that actually matters. Everything below is a second layer.',
  },
  {
    name: 'Roku',
    tier: 'Device level',
    steps: [
      'Settings → Parental controls → set a 4-digit PIN.',
      'Turn on the PIN requirement for adding channels, so nothing new gets installed without you.',
      'Inside The Roku Channel, set a content-rating limit — this is separate from the device PIN and people miss it.',
      'Use the Kids & Family row as the default landing place for the 10-year-old.',
    ],
    why: 'Roku has no user profiles, so the PIN plus the channel-level rating limit is the whole of what the device itself offers. Pair it with the DNS filtering above.',
  },
  {
    name: 'Tubi',
    tier: 'App level',
    steps: [
      'Open the profile menu → Parental Controls → set a PIN and a maximum content rating.',
      'Switch the child to Tubi Kids, which is a separate locked-down mode rather than a filter.',
    ],
    why: 'Tubi has the largest library here and therefore the most to filter. Its horror catalogue is genuinely extreme, so the rating cap is not optional if a child uses the same app.',
  },
  {
    name: 'Pluto TV',
    tier: 'App level',
    steps: ['Switch to Kids Mode from the main menu and set the exit PIN.'],
    why: 'Kids Mode replaces the entire channel grid rather than hiding rows, so there is nothing to stumble into.',
  },
  {
    name: 'YouTube',
    tier: 'App level',
    star: true,
    steps: [
      'For the 6–12 year old: use the separate YouTube Kids app, not main YouTube with Restricted Mode.',
      'For the teen: a supervised Google account on main YouTube gives you content settings plus history visibility.',
      'Turn off autoplay in both.',
    ],
    why: 'Main YouTube\'s Restricted Mode is a filter with known gaps. YouTube Kids is a different, much smaller catalogue — a walled garden rather than a sieve. For a 10-year-old that difference is the whole ballgame.',
  },
  {
    name: 'PBS Kids and Kanopy Kids',
    tier: 'No setup needed',
    steps: ['Nothing to configure.'],
    why: 'Neither platform contains adult content, so there is nothing to filter and no ads to police. When you want zero supervision overhead, these are the two to hand over.',
  },
];

/* ------------------------------------------------------------------ *
 * MOODS — the tonight curator                                         *
 * ------------------------------------------------------------------ */

const MOODS = [
  { id: 'fried', label: 'Brain is fried', hint: 'Nothing to follow, nothing to decide' },
  { id: 'wired', label: 'Want something intense', hint: 'Give me a plot to chase' },
  { id: 'creeped', label: 'Want to be creeped out', hint: 'Dread over gore, or gore — your call' },
  { id: 'laughs', label: 'Just want to laugh', hint: 'No commitment, no continuity' },
  { id: 'awe', label: 'Want to feel something', hint: 'Beautiful, strange, slow' },
  { id: 'curious', label: 'Want to learn something', hint: 'Documentary and lecture' },
  { id: 'company', label: 'Want background noise', hint: 'Half-watching while doing something else' },
];

const TIMES = [
  { id: 20, label: 'Under 20 min' },
  { id: 45, label: 'About 45 min' },
  { id: 100, label: 'A film-length evening' },
  { id: 999, label: 'All night, no limit' },
];

const PROFILES = [
  { id: 'adult', label: 'Adults', maxAge: 99 },
  { id: 'teen', label: 'Teen (13+)', maxAge: 15 },
  { id: 'kid', label: 'Kids (6–12)', maxAge: 10 },
];
